// Code generated by config_gen.go; DO NOT EDIT.
// Generated from network: tiny
package constants

const NumTicketEntries int = 3

const TicketSubmissionEndingSlotPhaseNumber uint32 = 10 // Y

const MaxItemsInAuthorizationsPool uint16 = 8 // O

const ValidatorCoreAssignmentsRotationPeriodInTimeslots uint16 = 4 // R

const SegmentSize uint32 = 4104 // W_G

const ErasureCodedPiecesSize uint32 = 4 // W_E

const ErasureCodedPiecesInSegment uint32 = 1026 // W_P

const UnreferencePreimageExpungeTimeslots uint32 = 6 // D

const NumValidators uint16 = 6 // V

const NumCores uint16 = 2 // C

const NumTimeslotsPerEpoch uint32 = 12 // E

const MaxTicketsPerExtrinsic uint16 = 3 // K

const AuthorizerQueueLength uint16 = 80 // Q

// Additional constants
const IsAuthorizedCodeMaxSizeOctets uint32 = 64000 // W_A

const ServiceCodeMaxSize uint32 = 4000000 // W_C

const RecentHistorySizeBlocks uint16 = 8 // H

const AccumulationQueueMaxEntries uint16 = 1024 // S

const IsAuthorizedGasAllocation uint64 = 50000000 // G_I

const MaxImportsInWorkPackage uint32 = 3072 // W_M

const MaxExportsInWorkPackage uint32 = 3072 // W_X

const LookupAnchorMaxAgeTimeslots uint32 = 14400 // L

const ServiceMinimumBalance uint64 = 100 // B_S

const MaxSumDependencyItemsInReport uint16 = 8 // J

const RefineGasAllocation uint64 = 5000000000 // G_R

const AllAccumulationTotalGasAllocation uint64 = 3500000000 // G_T

const MaxExtrinsicsInWorkPackage uint16 = 128 // T

const ServiceMinimumBalancePerOctet uint64 = 1 // B_L

const DynamicAddressAlignmentFactor int = 2 // Z_A

const TransferMemoSize uint32 = 128 // W_T

const MaxSizeEncodedWorkPackage uint32 = 12 << 20 // W_B

const ServiceMinimumBalancePerItem uint64 = 10 // B_I

const UnavailableWorkTimeoutTimeslots uint16 = 5 // U

const MaxWorkItemsInPackage uint16 = 16 // I

const SingleAccumulationAllocatedGas uint64 = 10000000 // G_A

const MaxTotalSizeWorkReportBlobs uint32 = 48 << 10 // W_R

const SlotPeriodInSeconds uint16 = 6 // P

// Derived constants
const TwoThirdsNumValidators uint16 = 2 * NumValidators / 3
const NumValidatorSafetyThreshold uint16 = TwoThirdsNumValidators + 1
const OneThirdNumValidators uint16 = NumValidators / 3
