// Code generated by constants_gen.go; DO NOT EDIT.
package constants

const MaxItemsInAuthorizationsPool int = 8

const MaxWorkItemsInPackage int = 4

const ServiceCodeMaxSize int = 4000000

const SingleAccumulationAllocatedGas int = 10000000

const RecentHistorySizeBlocks int = 8

const UnavailableWorkTimeoutTimeslots int = 5

const ServiceMinimumBalance int = 100

const NumValidators int = 6

const NumTimeslotsPerEpoch int = 12

const TicketSubmissionEndingSlotPhaseNumber int = 500

const ValidatorCoreAssignmentsRotationPeriodInTimeslots int = 4

const ServiceMinimumBalancePerItem int = 10

const ServiceMinimumBalancePerOctet int = 1

const TotalAccumulationAllocatedGas int = 3500000000

const NumTicketEntries int = 3

const NumCores int = 2

const AuthorizerQueueLength int = 80

const TwoThirdsNumValidators int = 2 * NumValidators / 3

const NumValidatorSafetyThreshold int = TwoThirdsNumValidators + 1

const OneThirdNumValidators int = NumValidators / 3

