// Code generated by constants_gen.go; DO NOT EDIT.
package constants

const MaxItemsInAuthorizationsPool uint16 = 8 // O

const ValidatorCoreAssignmentsRotationPeriodInTimeslots uint16 = 4 // R

const AccumulationQueueMaxEntries uint16 = 1024 // S

const MaxExtrinsicsInWorkPackage uint16 = 128 // T

const IsAuthorizedCodeMaxSizeOctets uint32 = 64000 // W_A

const MaxSizeEncodedWorkPackage uint32 = 12 << 20 // W_B

const ServiceCodeMaxSize uint32 = 4000000 // W_C

const NumTimeslotsPerEpoch uint32 = 12 // E

const NumCores uint16 = 2 // C

const ServiceMinimumBalance uint64 = 100 // B_S

const ServiceMinimumBalancePerItem uint64 = 10 // B_I

const ServiceMinimumBalancePerOctet uint64 = 1 // B_L

const TotalAccumulationAllocatedGas int = 3500000000

const RecentHistorySizeBlocks uint16 = 8 // H

const NumValidators uint16 = 6 // V

const TicketSubmissionEndingSlotPhaseNumber uint32 = 500 // Y

const UnavailableWorkTimeoutTimeslots uint16 = 5 // U

const MaxWorkItemsInPackage uint16 = 16 // I

const MaxSumDependencyItemsInReport uint16 = 8 // J

const SingleAccumulationAllocatedGas uint64 = 10000000 // G_A

const AuthorizerQueueLength uint16 = 80 // Q

const NumTicketEntries int = 3

const TwoThirdsNumValidators uint16 = 2 * NumValidators / 3

const NumValidatorSafetyThreshold uint16 = TwoThirdsNumValidators + 1

const OneThirdNumValidators uint16 = NumValidators / 3

const DynamicAddressAlignmentFactor = 2

const IsAuthorizedGasAllocation uint64 = 50000000 // G_I

const RefineGasAllocation uint64 = 5000000000 // G_R

const AllAccumulationTotalGasAllocation uint64 = 3500000000 // G_T

const ErasureCodedPiecesSize uint32 = 684 // W_E

const SegmentSize uint32 = ErasureCodedPiecesInSegment * ErasureCodedPiecesSize // W_G

const MaxImportsInWorkPackage uint32 = 3072 // W_M

const ErasureCodedPiecesInSegment uint32 = 6 // W_P

const MaxTotalSizeWorkReportBlobs uint32 = 48 << 10 // W_R

const WorkPackageManifestMaxEntries int = (1 << 11)

const TransferMemoSize uint32 = 128 // W_T

const MaxExportsInWorkPackage uint32 = 3072 // W_X

const UnreferencePreimageExpungeTimeslots uint32 = 19200 // D

const LookupAnchorMaxAgeTimeslots uint32 = 14400 // L

const SlotPeriodInSeconds uint16 = 6 // P