//go:build ignore
// +build ignore

package main

import (
	"fmt"
	"os"
)

// Constants sets - production vs test
var productionConstants = map[string]int{
	"NumValidators":                                     1023,
	"NumTicketEntries":                                  2,
	"NumTimeslotsPerEpoch":                              600,
	"TicketSubmissionEndingSlotPhaseNumber":             500,
	"NumCores":                                          341,
	"AuthorizerQueueLength":                             80,
	"MaxItemsInAuthorizationsPool":                      8,
	"ValidatorCoreAssignmentsRotationPeriodInTimeslots": 10,
	"UnavailableWorkTimeoutTimeslots":                   5,
	"MaxWorkItemsInPackage":                             4,
	"ServiceCodeMaxSize":                                4000000,
	"ServiceMinimumBalance":                             100,
	"ServiceMinimumBalancePerItem":                      10,
	"ServiceMinimumBalancePerOctet":                     1,
	"SingleAccumulationAllocatedGas":                    10000000,
	"TotalAccumulationAllocatedGas":                     3500000000,
	"RecentHistorySizeBlocks":                           8,
}

var testConstants = map[string]int{
	"NumValidators":                                     6,
	"NumTicketEntries":                                  3,
	"NumTimeslotsPerEpoch":                              12,
	"TicketSubmissionEndingSlotPhaseNumber":             500,
	"NumCores":                                          2,
	"AuthorizerQueueLength":                             80,
	"MaxItemsInAuthorizationsPool":                      8,
	"ValidatorCoreAssignmentsRotationPeriodInTimeslots": 4,
	"UnavailableWorkTimeoutTimeslots":                   5,
	"MaxWorkItemsInPackage":                             4,
	"ServiceCodeMaxSize":                                4000000,
	"ServiceMinimumBalance":                             100,
	"ServiceMinimumBalancePerItem":                      10,
	"ServiceMinimumBalancePerOctet":                     1,
	"SingleAccumulationAllocatedGas":                    10000000,
	"TotalAccumulationAllocatedGas":                     3500000000,
	"RecentHistorySizeBlocks":                           8,
}

func main() {
	useTestValues := os.Getenv("JAM_USE_TEST_CONSTANTS") == "true"

	constants := productionConstants
	if useTestValues {
		constants = testConstants
	}

	f, err := os.Create("constants.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	fmt.Fprintln(f, "// Code generated by constants_gen.go; DO NOT EDIT.")
	fmt.Fprintln(f, "package constants")
	fmt.Fprintln(f)

	// Write primary constants
	for name, value := range constants {
		fmt.Fprintf(f, "const %s int = %d\n\n", name, value)
	}

	// Write derived constants
	fmt.Fprintln(f, "const TwoThirdsNumValidators int = 2 * NumValidators / 3\n")
	fmt.Fprintln(f, "const NumValidatorSafetyThreshold int = TwoThirdsNumValidators + 1\n")
	fmt.Fprintln(f, "const OneThirdNumValidators int = NumValidators / 3\n")
}
