package pvm

func init() {

	dispatchTable = [256]*InstructionInfo{
		0:   {Handler: handleTrap, ExtractOperands: extractTrap},
		1:   {Handler: handleFallthrough, ExtractOperands: extractFallthrough},
		10:  {Handler: handleEcalli, ExtractOperands: extractEcalli},
		20:  {Handler: handleLoadImm64, ExtractOperands: extractLoadImm64},
		30:  {Handler: handleTwoImmValues, ExtractOperands: extractTwoImmValues},
		31:  {Handler: handleTwoImmValues, ExtractOperands: extractTwoImmValues},
		32:  {Handler: handleTwoImmValues, ExtractOperands: extractTwoImmValues},
		33:  {Handler: handleTwoImmValues, ExtractOperands: extractTwoImmValues},
		40:  {Handler: handleJump, ExtractOperands: extractJump},
		50:  {Handler: handleOneRegOneImm, ExtractOperands: extractOneRegOneImm},
		51:  {Handler: handleOneRegOneImm, ExtractOperands: extractOneRegOneImm},
		52:  {Handler: handleOneRegOneImm, ExtractOperands: extractOneRegOneImm},
		53:  {Handler: handleOneRegOneImm, ExtractOperands: extractOneRegOneImm},
		54:  {Handler: handleOneRegOneImm, ExtractOperands: extractOneRegOneImm},
		55:  {Handler: handleOneRegOneImm, ExtractOperands: extractOneRegOneImm},
		56:  {Handler: handleOneRegOneImm, ExtractOperands: extractOneRegOneImm},
		57:  {Handler: handleOneRegOneImm, ExtractOperands: extractOneRegOneImm},
		58:  {Handler: handleOneRegOneImm, ExtractOperands: extractOneRegOneImm},
		59:  {Handler: handleOneRegOneImm, ExtractOperands: extractOneRegOneImm},
		60:  {Handler: handleOneRegOneImm, ExtractOperands: extractOneRegOneImm},
		61:  {Handler: handleOneRegOneImm, ExtractOperands: extractOneRegOneImm},
		62:  {Handler: handleOneRegOneImm, ExtractOperands: extractOneRegOneImm},
		70:  {Handler: handleOneRegTwoImm, ExtractOperands: extractOneRegTwoImm},
		71:  {Handler: handleOneRegTwoImm, ExtractOperands: extractOneRegTwoImm},
		72:  {Handler: handleOneRegTwoImm, ExtractOperands: extractOneRegTwoImm},
		73:  {Handler: handleOneRegTwoImm, ExtractOperands: extractOneRegTwoImm},
		80:  {Handler: handleOneRegOneImmOneOff, ExtractOperands: extractOneRegOneImmOneOff},
		81:  {Handler: handleOneRegOneImmOneOff, ExtractOperands: extractOneRegOneImmOneOff},
		82:  {Handler: handleOneRegOneImmOneOff, ExtractOperands: extractOneRegOneImmOneOff},
		83:  {Handler: handleOneRegOneImmOneOff, ExtractOperands: extractOneRegOneImmOneOff},
		84:  {Handler: handleOneRegOneImmOneOff, ExtractOperands: extractOneRegOneImmOneOff},
		85:  {Handler: handleOneRegOneImmOneOff, ExtractOperands: extractOneRegOneImmOneOff},
		86:  {Handler: handleOneRegOneImmOneOff, ExtractOperands: extractOneRegOneImmOneOff},
		87:  {Handler: handleOneRegOneImmOneOff, ExtractOperands: extractOneRegOneImmOneOff},
		88:  {Handler: handleOneRegOneImmOneOff, ExtractOperands: extractOneRegOneImmOneOff},
		89:  {Handler: handleOneRegOneImmOneOff, ExtractOperands: extractOneRegOneImmOneOff},
		90:  {Handler: handleOneRegOneImmOneOff, ExtractOperands: extractOneRegOneImmOneOff},
		100: {Handler: handleTwoReg, ExtractOperands: extractTwoReg},
		101: {Handler: handleTwoReg, ExtractOperands: extractTwoReg},
		102: {Handler: handleTwoReg, ExtractOperands: extractTwoReg},
		103: {Handler: handleTwoReg, ExtractOperands: extractTwoReg},
		104: {Handler: handleTwoReg, ExtractOperands: extractTwoReg},
		105: {Handler: handleTwoReg, ExtractOperands: extractTwoReg},
		106: {Handler: handleTwoReg, ExtractOperands: extractTwoReg},
		107: {Handler: handleTwoReg, ExtractOperands: extractTwoReg},
		108: {Handler: handleTwoReg, ExtractOperands: extractTwoReg},
		109: {Handler: handleTwoReg, ExtractOperands: extractTwoReg},
		110: {Handler: handleTwoReg, ExtractOperands: extractTwoReg},
		111: {Handler: handleTwoReg, ExtractOperands: extractTwoReg},
		120: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		121: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		122: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		123: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		124: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		125: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		126: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		127: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		128: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		129: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		130: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		131: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		132: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		133: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		134: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		135: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		136: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		137: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		138: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		139: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		140: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		141: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		142: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		143: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		144: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		145: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		146: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		147: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		148: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		149: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		150: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		151: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		152: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		153: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		154: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		155: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		156: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		157: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		158: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		159: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		160: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		161: {Handler: handleTwoRegOneImm, ExtractOperands: extractTwoRegOneImm},
		170: {Handler: handleTwoRegOneOffset, ExtractOperands: extractTwoRegOneOffset},
		171: {Handler: handleTwoRegOneOffset, ExtractOperands: extractTwoRegOneOffset},
		172: {Handler: handleTwoRegOneOffset, ExtractOperands: extractTwoRegOneOffset},
		173: {Handler: handleTwoRegOneOffset, ExtractOperands: extractTwoRegOneOffset},
		174: {Handler: handleTwoRegOneOffset, ExtractOperands: extractTwoRegOneOffset},
		175: {Handler: handleTwoRegOneOffset, ExtractOperands: extractTwoRegOneOffset},
		180: {Handler: handleLoadImmJumpInd, ExtractOperands: extractLoadImmJumpInd},
		190: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		191: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		192: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		193: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		194: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		195: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		196: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		197: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		198: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		199: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		200: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		201: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		202: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		203: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		204: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		205: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		206: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		207: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		208: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		209: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		210: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		211: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		212: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		213: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		214: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		215: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		216: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		217: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		218: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		219: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		220: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		221: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		222: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		223: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		224: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		225: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		226: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		227: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		228: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		229: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
		230: {Handler: handleThreeReg, ExtractOperands: extractThreeReg},
	}

	terminationOpcodes = [256]bool{
		0:   true,
		1:   true,
		40:  true,
		50:  true,
		80:  true,
		81:  true,
		82:  true,
		83:  true,
		84:  true,
		85:  true,
		86:  true,
		87:  true,
		88:  true,
		89:  true,
		90:  true,
		170: true,
		171: true,
		172: true,
		173: true,
		174: true,
		175: true,
		180: true,
	}
}
