// Code generated by config_gen.go; DO NOT EDIT.
// Generated from network: tiny
package constants

// Config constants
const AllAccumulationTotalGasAllocation uint64 = 20000000 // G_T

const ErasureCodedPiecesInSegment uint32 = 1026 // W_P

const ErasureCodedPiecesSize uint32 = 4 // W_E

const MaxTicketsPerExtrinsic uint16 = 3 // K

const NumCores uint16 = 2 // C

const NumTicketEntries uint16 = 3 // N

const NumTimeslotsPerEpoch uint32 = 12 // E

const NumValidators uint16 = 6 // V

const RefineGasAllocation uint64 = 1000000000 // G_R

const SlotPeriodInSeconds uint16 = 6 // P

const TicketSubmissionEndingSlotPhaseNumber uint32 = 10 // Y

const UnreferencePreimageExpungeTimeslots uint32 = 32 // D

const ValidatorCoreAssignmentsRotationPeriodInTimeslots uint16 = 4 // R

// Additional constants
const AuthorizerQueueLength uint16 = 80 // Q

const DynamicAddressAlignmentFactor int = 2 // Z_A

const IsAuthorizedCodeMaxSizeOctets uint32 = 64000 // W_A

const IsAuthorizedGasAllocation uint64 = 50000000 // G_I

const JamCommonEraStartUnixTime int64 = 1735732800 // JCE epoch (2025-01-01 12:00 UTC)

const LookupAnchorMaxAgeTimeslots uint32 = 14400 // L

const MaxExportsInWorkPackage uint32 = 3072 // W_X

const MaxExtrinsicsInWorkPackage uint16 = 128 // T

const MaxImportsInWorkPackage uint32 = 3072 // W_M

const MaxItemsInAuthorizationsPool uint16 = 8 // O

const MaxSizeEncodedWorkPackage uint32 = 13794305 // W_B

const MaxSumDependencyItemsInReport uint16 = 8 // J

const MaxTotalSizeWorkReportBlobs uint32 = 48 << 10 // W_R

const MaxWorkItemsInPackage uint16 = 16 // I

const RecentHistorySizeBlocks uint16 = 8 // H

const ServiceCodeMaxSize uint32 = 4000000 // W_C

const ServiceMinimumBalance uint64 = 100 // B_S

const ServiceMinimumBalancePerItem uint64 = 10 // B_I

const ServiceMinimumBalancePerOctet uint64 = 1 // B_L

const SingleAccumulationAllocatedGas uint64 = 10000000 // G_A

const TransferMemoSize uint32 = 128 // W_T

const UnavailableWorkTimeoutTimeslots uint16 = 5 // U

// Derived constants
const TwoThirdsNumValidators uint16 = 2 * NumValidators / 3
const NumValidatorSafetyThreshold uint16 = TwoThirdsNumValidators + 1
const OneThirdNumValidators uint16 = NumValidators / 3
const SegmentSize uint32 = ErasureCodedPiecesSize * ErasureCodedPiecesInSegment
const RecoveryThreshold uint32 = ErasureCodedPiecesSize / 2
